### PR TITLE
Made top bar slightly bigger

### PR DESCRIPTION
**Pull request by Serubin**
Copy of #58 with added experiments integration.

### CODE REVIEW

**Comment by Serubin** [comment]
@klinker24 Does this look okay to you?

**Comment by klinker24** [comment]
I will have some time to test it out later today 😃 been out of town at the end of the week. Code looked good, just need to download and play with it!

**Comment by Serubin** [comment]
Sounds good!

**Comment by FliiFe** [comment]
This is perfect, the experiment thing is a great idea !
Works perfectly fine as well

**Pull request merged**
